name: Publish Checkmarx MCP Server

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  publish:
    name: Publish MCP Server
    uses: Checkmarx/github-actions-library/.github/workflows/publish-mcp-server.yaml@cccf47f10f33bdf9a0efc264c3537c39e56c263c
    secrets:
      MCP_TOKEN: ${{ secrets.MCP_TOKEN }}
